version: '3.8'
services:
  deeppavlov_lab:
    build: .
    volumes:
      # Пробрасываем папку с кодом
      - ./notebooks:/app/notebooks
      # Пробрасываем папку для моделей
      - ./models:/root/.deeppavlov 
    ports:
      - "8888:8888"
    environment:
      - DP_MODELS_PATH=/root/.deeppavlov
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]